// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromomashInc.Server.Context;

#nullable disable

namespace PromomashInc.Server.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20240711224346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("PromomashInc.Server.Context.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayText")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("PromomashInc.Server.Context.Province", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("PromomashInc.Server.Context.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
